### ISSUE TITLE
Fix Theming for APK docs - Mkdocs 1.0.4

### ISSUE THREAD

**Issue by Mariangela** [wso2/docs-apk#54]
### **Description:**
Fix the theming for APK docs for Mkdocs 1.0.4 with Python 3.6

- [x] - Fix the banner
- [x] - Add white spacing where need
- [x] - Increase side margins
- [x] - Decide on a primary and accent color.
- [x] - Fix the doc search
- [ ]  - Add the Feedback button
- [ ] - Add whatever other improvements to the theme

-----------
### **Summary of issues with the new theming**
- [x] [Copyrights need to be added](https://github.com/wso2/docs-apk/issues/54#issuecomment-1461179860)
- [ ] [Need to add home icon](https://github.com/wso2/docs-apk/issues/54#issuecomment-1461225084)
- [ ] [WIP banner not visible in mobile view](https://github.com/wso2/docs-apk/issues/54#issuecomment-1461240461)
- [ ] [Mismatch in the size of the bullets and regular text](https://github.com/wso2/docs-apk/issues/54#issuecomment-1461248007)
- [ ] [Normal space between H1 and content too much](https://github.com/wso2/docs-apk/issues/54#issuecomment-1461248007)
- [ ] [When heading is long space after H1 is more](https://github.com/wso2/docs-apk/issues/54#issuecomment-1461355981)
- [x] [The Copyrights statement does not appear at the bottom of the home page.](https://github.com/wso2/docs-apk/issues/54#issuecomment-1461867180)

**Comment by Mariangela** [comment]
**Update**

I had a discussion with Chanaka today in the morning to explain the tasks that he had to do.

**Comment by chanaka3d** [comment]
![screencapture-localhost-8000-about-apk-what-is-apk-2023-03-08-21_00_53](https://user-images.githubusercontent.com/3424539/223764595-db420214-bffc-4913-a11f-7cdc61828faf.png)



![screencapture-localhost-8000-2023-03-08-21_01_31](https://user-images.githubusercontent.com/3424539/223764879-d5847607-9818-4b28-a337-956e513787b0.png)



<img width="1125" alt="Screen Shot 2023-03-08 at 9 29 21 PM" src="https://user-images.githubusercontent.com/3424539/223764930-cf950fa7-7d96-44cc-99b3-0767dd66aabe.png">


PR without the Feedback and Doc search.


https://github.com/wso2/docs-apk/pull/61

**Comment by Mariangela** [comment]
@chanaka3d , we need to add the following copyrights statement. Similar to APIM [1]


Copyright © [WSO2 LLC](https://wso2.com/) (2023)
Content licensed under [CC By 4.0.](https://creativecommons.org/licenses/by/4.0) | Sample code licensed under [Apache 2.0](http://www.apache.org/licenses/).

[1] https://apim.docs.wso2.com/en/latest/

**Comment by Mariangela** [comment]
It will be nice to have the home icon of the little house as well similar to [1]

[1] https://apim.docs.wso2.com/en/latest/

**Comment by Mariangela** [comment]
The Work in process icon is not properly visible on a lower resolution, as in when looking at this on a mobile phone.
![WhatsApp Image 2023-03-09 at 9 22 41 AM (1)](https://user-images.githubusercontent.com/5195851/223913602-f029489d-61c6-43c4-99b2-e35e2daee8fa.jpeg)

![WhatsApp Image 2023-03-09 at 9 22 41 AM](https://user-images.githubusercontent.com/5195851/223913610-822a2859-6ab9-4f75-a74f-6df5eebfa9ea.jpeg)

**Comment by Mariangela** [comment]
There is a mismatch in the size of the bullets and regular text used for it. At times the text of the bullet looks larger and the regular text that follows the font and wise versa.

<img width="906" alt="Screenshot 2023-03-09 at 9 36 46 AM" src="https://user-images.githubusercontent.com/5195851/223914529-24387fcb-5373-4fc4-bb14-2744edf61b69.png">

**Comment by Mariangela** [comment]
Space between heading 1 and content looks too much
<img width="1474" alt="Screenshot 2023-03-09 at 11 38 26 AM" src="https://user-images.githubusercontent.com/5195851/223935682-539b8947-3b05-490d-bfe9-2f584d1d92da.png">

**Comment by Mariangela** [comment]
Space between heading increases more when heading is long
<img width="1267" alt="Screenshot 2023-03-09 at 11 43 04 AM" src="https://user-images.githubusercontent.com/5195851/223936539-96c357bf-777b-4270-b169-68d34ffc171e.png">

**Comment by Mariangela** [comment]
The Copyrights statement does not appear at the bottom of the home page.
<img width="1728" alt="Screenshot 2023-03-09 at 5 07 39 PM" src="https://user-images.githubusercontent.com/5195851/224012194-ffa10a5a-27ee-407d-ad04-93875e2f39c7.png">
