### ISSUE TITLE
[Epic] Making the APK docs Live

### ISSUE THREAD

**Issue by Mariangela** [wso2/docs-apk#55]
**Description:**
The following are the sub tasks related to this task.

- [x] https://github.com/wso2/docs-apk/issues/34
- [x] https://github.com/wso2/docs-apk/issues/35
- [x] https://github.com/wso2/docs-apk/issues/36
- [ ] https://github.com/wso2/docs-apk/issues/54

**Comment by Mariangela** [comment]
**Snapshot of the status**

<google-sheets-html-origin><style type="text/css"></style>

  | Task[A] | Status[B] | Comment[C] | Workaround[D] | Resource Requirement/Need Help[E]
-- | -- | -- | -- | -- | --
1 | Finalize document framework to be use for APK(check Choreo, Asgardeo, ballerina and come to conclusion.) | Completed | Decided to use the latest version of Mkdocs | - | -
https://docs.google.com/spreadsheets/d/1ESCJS2k8UeoAGZAQdLUUuziSXpxWqouq6_fLNspazNQ/edit#gid=1738702184
2 | Setting up selected platform on cloud infrastructure and have live link to access through internet. Document version should be 1.0.0 developer preview. | Completed | On 3rd March digi-ops gave us a way to access the APK doc site, which had dummy content, internally.15.197.208.33 apk.docs.wso2.com | - | -
On 7th March digi-ops gave us the live URLhttps://apk.docs.wso2.com/en/latest/
3 | Have API docs with initial formatting and base contents we have right now. And when we commit something to github location of document it need to be automatically publish to APK live document. | In-progress | Build is failing with Mkdocs 1.4.2 on Python 3.11 due to dependency issues. | Downgraded the Python version to 3.9 |  
Build is failing with Mkdocs 1.4.2 on Python 3.9 due to theming issues. | Backed up the build script and went back to using the build script that was compatible with Mkdocs 1.0.4 & Python 3.6, which is almost identical to the APIM build script | 3.1) Need help to fix the APK build script so that it supports Mkdocs 1.4.2 with Python 3.9
Docs are live on Mkdocs 1.0.4 using Python 3.6https://apk.docs.wso2.com/en/latest/ |   | 3.2) It will be good if there is another Jenkins build job to troubleshoot the APK docs build which uses Mkdocs 1.4.2 with Python 3.9.
3.3) Need a resource to fix the theming issues

"Task
[A]"	"Status
[B]"	"Comment
[C]"	"Workaround
[D]"	"Resource Requirement/
Need Help
[E]"
1	Finalize document framework to be use for APK(check Choreo, Asgardeo, ballerina and come to conclusion.)	Completed	Decided to use the latest version of Mkdocs	-	-
			https://docs.google.com/spreadsheets/d/1ESCJS2k8UeoAGZAQdLUUuziSXpxWqouq6_fLNspazNQ/edit#gid=1738702184		
2	Setting up selected platform on cloud infrastructure and have live link to access through internet. Document version should be 1.0.0 developer preview. 	Completed	"On 3rd March digi-ops gave us a way to access the APK doc site, which had dummy content, internally.

15.197.208.33 
apk.docs.wso2.com"	-	-
			"On 7th March digi-ops gave us the live URL
https://apk.docs.wso2.com/en/latest/"		
3	Have API docs with initial formatting and base contents we have right now. And when we commit something to github location of document it need to be automatically publish to APK live document.	In-progress	"Build is failing with Mkdocs 1.4.2 on Python 3.11 due to dependency issues.
"	Downgraded the Python version to 3.9	
			"Build is failing with Mkdocs 1.4.2 on Python 3.9 due to theming issues.
"	Backed up the build script and went back to using the build script that was compatible with Mkdocs 1.0.4 & Python 3.6, which is almost identical to the APIM build script	"3.1) 
Need help to fix the APK build script so that it supports Mkdocs 1.4.2 with Python 3.9"
			"Docs are live on Mkdocs 1.0.4 using Python 3.6
https://apk.docs.wso2.com/en/latest//"		"3.2) 
It will be good if there is another Jenkins build job to troubleshoot the APK docs build which uses Mkdocs 1.4.2 with Python 3.9."
					"3.3) 
Need a resource to fix the theming issues"

**Comment by Mariangela** [comment]
**Snapshot of the status**
<img width="1053" alt="Screenshot 2023-03-08 at 12 10 10 PM" src="https://user-images.githubusercontent.com/5195851/223638285-7d0977ff-5539-4d5e-9e03-115a94d676d7.png">

**Comment by Mariangela** [comment]
### Update
(3.1) Chanaka is working on this task in https://github.com/wso2/docs-apk/issues/55

(3.2) 
Sent an email to get another  Jenkins job
Email: Request to create a job for docs-apk-dev build
-------

As the APK docs on Mkdocs 1.0.4 is in an ok condition, I am closing this task.
